# Generated by Django 5.1.1 on 2024-09-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad_cliente', models.IntegerField()),
                ('cantidad_dependientes', models.IntegerField()),
                ('meses_en_libro', models.IntegerField()),
                ('total_relaciones', models.IntegerField()),
                ('meses_inactivo_12', models.IntegerField()),
                ('contactos_12_meses', models.IntegerField()),
                ('saldo_revolvente', models.FloatField()),
                ('promedio_disponible', models.FloatField()),
                ('cambio_monto_q4_q1', models.FloatField()),
                ('monto_total_transacciones', models.FloatField()),
                ('total_transacciones', models.IntegerField()),
                ('cambio_total_transacciones_q4_q1', models.FloatField()),
                ('promedio_utilizacion', models.FloatField()),
                ('genero_masculino', models.BooleanField()),
                ('nivel_educacion_doctorado', models.BooleanField()),
                ('nivel_educacion_graduado', models.BooleanField()),
                ('nivel_educacion_preparatoria', models.BooleanField()),
                ('nivel_educacion_postgrado', models.BooleanField()),
                ('nivel_educacion_sin_educacion', models.BooleanField()),
                ('nivel_educacion_desconocido', models.BooleanField()),
                ('estado_civil_casado', models.BooleanField()),
                ('estado_civil_soltero', models.BooleanField()),
                ('estado_civil_desconocido', models.BooleanField()),
                ('ingreso_40k_60k', models.BooleanField()),
                ('ingreso_60k_80k', models.BooleanField()),
                ('ingreso_80k_120k', models.BooleanField()),
                ('ingreso_menor_40k', models.BooleanField()),
                ('ingreso_desconocido', models.BooleanField()),
                ('categoria_tarjeta_oro', models.BooleanField()),
                ('categoria_tarjeta_platino', models.BooleanField()),
                ('categoria_tarjeta_plata', models.BooleanField()),
            ],
        ),
    ]
