# Generated by Django 5.1.1 on 2024-09-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card', '0003_remove_prospecto_card_category_silver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecto',
            name='card_category_silver',
            field=models.BooleanField(default=False),
        ),
    ]
