# Generated by Django 5.1.1 on 2024-09-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card', '0004_prospecto_card_category_silver'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecto',
            name='customer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
