# Generated by Django 5.1.1 on 2024-09-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card', '0006_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusName', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
    ]
