# Generated by Django 5.1.1 on 2024-09-17 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card', '0007_status_alter_solicitud_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='status',
            field=models.ForeignKey(default=1, max_length=250, on_delete=django.db.models.deletion.RESTRICT, to='credit_card.status'),
            preserve_default=False,
        ),
    ]
